FROM openjdk:8

# install needed packages
RUN apt-get update && apt-get install -y ant  && apt-get install -y zip && apt-get install -y xmlstarlet 

# Install pre-requisite packages for Powershell .
RUN apt-get install -y wget  && apt-get install -y libicu-dev
# Download the PowerShell package file
RUN wget https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/powershell_7.4.0-1.deb_amd64.deb
# Install the PowerShell package
RUN dpkg -i powershell_7.4.0-1.deb_amd64.deb

RUN mkdir -p izpack

COPY /ant-lib /usr/share/ant/lib/
COPY . izpack
WORKDIR /izpack
RUN ant -file src/build.xml all
