FROM openjdk:11

# install needed packages
RUN apt-get update && apt-get install -y ant  && apt-get install -y zip && apt-get install -y xmlstarlet
# apt install openjdk-11-jre-headless
RUN mkdir -p izpack
RUN apt-get update && apt-get install -y powershell

COPY /ant-lib /usr/share/ant/lib/
COPY . izpack
WORKDIR /izpack
# RUN chmod 755 bin/compile.sh ==> Doesnt work


RUN cd  /izpack/
RUN git pull
RUN cd  /izpack/izPackCustomActions
						
# We need to compile SAGE Custom actions
RUN ant -file izPackCustomActions/build.xml all 

# COPY izPackCustomActions/bin/com.sage.izpack.jar /izpack/izPackCustomActions/com.sage.izpack.jar
