FROM openjdk:latest

# install needed packages
RUN apt-get update && apt-get install -y ant  && apt-get install -y zip
RUN mkdir -p izpack

COPY . izpack
WORKDIR /izpack
RUN ant -file src/build.xml all
  